### ISSUE TITLE
JSON doesn't parse anonymous object lists.

### ISSUE THREAD

**Issue by MajsterTynek** [ArowShot/MoreAdvancedMacros#1]
`require 'json' . parse ( '[{"foo":123},{"bar":456},{"baz":789}]' )`
![image](https://user-images.githubusercontent.com/13304376/87674099-cea14d00-c775-11ea-8108-f56fc1f06597.png)
found this out byt rying to parse response from
[Mojang API](https://wiki.vg/Mojang_API#Playernames_-.3E_UUIDs) (Playernames -> UUIDs; endpoint)

**Comment by MajsterTynek** [comment]
@ArowShot I have found fix for this issue!
```java
        library.set("parse", new OneArgFunction() {
            @Override
            public LuaValue call(LuaValue arg) {
                String json = arg.checkjstring();
                JsonElement jsonElement = new JsonParser().parse(json);
                return toLua(jsonElement);
            }
        });
```

**Comment by ArowShot** [comment]
Thanks for reporting and fixing this.
